// A curated subset of lucide-react icons that make sense for a places
// directory. Kept as a plain string list (rather than importing every icon
// component) so the icon picker stays a simple grid — admin picks a name,
// we look the component up dynamically wherever it's rendered.
export const curatedIconNames = [
  'MapPin',
  'Compass',
  'Mountain',
  'TreePine',
  'Trees',
  'Leaf',
  'Waves',
  'Anchor',
  'Ship',
  'Tent',
  'Camera',
  'Sunrise',
  'Sunset',
  'Droplets',
  'Landmark',
  'Building2',
  'Castle',
  'Church',
  'BookOpen',
  'Binoculars',
  'Bird',
  'Fish',
  'Flower2',
  'Palette',
  'Sparkles',
  'Users',
  'Navigation',
  'Footprints',
  'Bike',
  'TrainFront',
  'Star',
  'Globe',
] as const;
